name: RSpec

# masterブランチへのPR時の実行
on:
  pull_request:
    branches: [main]
    
jobs:
  run_spec:
    name: Run spec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: RSpec
      run: |
        bundle
        bundle exec rspec